sudo: false
dist: trusty
language: python

python:
  - "3.6"

ache:
  pip: true
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gfortran-6
      - liblapack-dev

git:
  depth: 1
env:
  global:
    - MAKEFLAGS="-j 20"

before_script:
  

script:
  - cd src
  - rm -r -f ../exe/linux/
  - make clean
  - COMPILER=gcc6 CXX=g++-6 FC=gfortran-6 STATIC=no make -j 20 install
  - cd ..
  - #wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - #bash miniconda.sh -b -p $HOME/miniconda
  - #export PATH="$HOME/miniconda/bin:$PATH"
  - #conda update --yes conda
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - #conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas matplotlib nose
  - pip install --upgrade pip
  - pip install -r requirements.travis.txt
  - #pip install https://github.com/modflowpy/pymake/zipball/master
  - pip install --upgrade jupyter
  - pip install nbconvert
  - pip install nose-timer
  - pip install coveralls
  - pip install git+https://github.com/modflowpy/flopy.git@develop
  - pip install git+https://github.com/jtwhite79/pyemu.git@develop
  - export PYTHONPATH=$PYTHONPATH:.
  - #cd benchmarks
  - export PATH="./test_bin/linux:../test_bin/linux:../../test_bin/linux:$PATH"
  - #nosetests -v -w ./benchmarks travis_tests.py 
  - nosetests -v -w ./benchmarks ci_prep.py
  - nosetests -v -w ./benchmarks ies_test.py opt_test.py

notifications:
  email: true
